import { Flex } from "@chakra-ui/react";
import { Inter } from "@next/font/google";
import Head from "next/head";
import { Cursor } from "../components/Cursor";

import { GameWindow } from "../components/GameWindow";
import { Header } from "../components/Header";
import { LinksReferers } from "../components/LinksReferers";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction="column">
        <Header />
        <GameWindow />
        <Cursor />
        <LinksReferers />
      </Flex>
    </>
  );
}
